image: php:latest

before_script:
  - apt-get update -yqq
  - apt-get install git zip unzip -qq
  - rm composer.* vendor/ -Rf
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar require phpunit/phpunit
  - echo "memory_limit = 512M" >> /usr/local/etc/php/conf.d/custom.ini

stages:
  - check_syntax
  - unit_tests

job_lint:
  stage: check_syntax
  script:
    - chmod +x ./scripts -Rf
    - ./scripts/lint.sh App/
  only:
    - master

job_phpunit:
  stage: unit_tests
  script:
    - vendor/bin/phpunit --bootstrap init.php App/Tests
  only:
    - master
