language: php
php:
  - 5.6

before_install:
  - cd php

stages:
  - unit_tests

job_phpunit:
  stage: unit_tests
  script:
    - phpunit --bootstrap init.php --debug --coverage-text test App/Tests
  only:
    - master
