language: php
php:
  - 5.6

sudo: required
dist: trusty

before_install:
  - composer require --dev phpunit/phpunit
install:
  - composer install --no-interaction --ignore-platform-reqs

stages:
  - unit_tests

job_phpunit:
  stage: unit_tests
  script:
    - vendor/bin/phpunit --bootstrap init.php App/Tests
  only:
    - master
