language: php
php:
  - 5.6

before_script:
  - composer require squizlabs/php_codesniffer phpmd/phpmd sebastian/phpcpd phpunit/phpunit phploc/phploc

script:
  - vendor/bin/phpunit --bootstrap init.php App/Tests
  - chmod +x ./scripts -Rf
  - ./scripts/lint.sh App/
