language: php
php:
  - 5.6

before_script:
  - composer require phpunit/phpunit 5.7.5

stages:
  - unit_tests

job_phpunit:
  stage: unit_tests
  script:
    - ./vendor/bin/phpunit --bootstrap init.php App/Tests
  only:
    - master
