language: php
php:
  - 5.6

sudo: required
dist: trusty

before_script:
  - sudo apt-get update -yqq
  - sudo apt-get install git zip unzip -qq
  - sudo rm composer.* vendor/ -Rf
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar require squizlabs/php_codesniffer phpmd/phpmd sebastian/phpcpd phpunit/phpunit phploc/phploc
  - sudo echo "memory_limit = 512M" >> /usr/local/etc/php/conf.d/custom.ini

stages:
  - check_syntax
  - unit_tests
  - analyse_code

job_lint:
  stage: check_syntax
  script:
    - chmod +x ./scripts -Rf
    - ./scripts/lint.sh App/
  only:
    - master

job_phpunit:
  stage: unit_tests
  script:
    - vendor/bin/phpunit --bootstrap init.php App/Tests
  only:
    - master
    
job_phpcs:
  stage: analyse_code
  script:
    - php vendor/bin/phpcs --config-set ignore_errors_on_exit 1
    - php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
    - php vendor/bin/phpcs --standard=PSR2 App > phpcs.log
  artifacts:
    paths:
      - phpcs.log
  only:
    - master

job_phpmd:
  stage: analyse_code
  script:
    - vendor/bin/phpmd App text cleancode,codesize,design,unusedcode,naming --suffixes php --reportfile phpmd.log || true
  artifacts:
    paths:
      - phpmd.log
  only:
    - master

job_phploc:
  stage: analyse_code
  script:
    - vendor/bin/phploc App/ > phploc.log
  artifacts:
    paths:
      - phploc.log
  only:
    - master
    
job_phpcpd:
  stage: analyse_code
  script:
    - vendor/bin/phpcpd App/ > phpcpd.log ||true
  artifacts:
    paths:
      - phpcpd.log
  only:
    - master


