language: php
php:
  - 5.6

sudo: required
dist: trusty

before_script:
  - composer require --dev phpunit/phpunit

stages:
  - unit_tests

job_phpunit:
  stage: unit_tests
  script:
    - vendor/bin/phpunit --bootstrap init.php App/Tests
  only:
    - master
